# Generated by Django 2.0.4 on 2018-06-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('street_number', models.IntegerField(default=None, null=True)),
                ('street_name', models.CharField(default=None, max_length=200, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('zip_code', models.IntegerField(default=None, null=True)),
                ('home_email', models.EmailField(blank=True, default=None, max_length=200, null=True)),
                ('work_email', models.EmailField(blank=True, default=None, max_length=200, null=True)),
                ('home_phone', models.IntegerField(blank=True, default=None, null=True)),
                ('cell_phone', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
