# Generated by Django 2.0.4 on 2018-06-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lender',
            old_name='street_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='street_number',
        ),
    ]
