# Generated by Django 2.0.4 on 2018-06-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_auto_20180624_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lender',
            old_name='address',
            new_name='street_address',
        ),
    ]
