# Generated by Django 2.0.4 on 2018-06-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0003_auto_20180624_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
