# Generated by Django 2.0.4 on 2018-06-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0004_lender_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lender',
            old_name='home_email',
            new_name='personal_email',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='home_phone',
        ),
        migrations.AddField(
            model_name='lender',
            name='work_phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
