# Generated by Django 2.0.4 on 2018-06-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0006_lender_solicitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='solicitation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3),
        ),
    ]
