# Generated by Django 2.0.4 on 2018-06-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0008_auto_20180624_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='sba_504',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3),
        ),
        migrations.AddField(
            model_name='lender',
            name='sba_7a',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3),
        ),
        migrations.AddField(
            model_name='lender',
            name='sba_CAPline',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3),
        ),
        migrations.AddField(
            model_name='lender',
            name='sba_micro',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3),
        ),
        migrations.AddField(
            model_name='lender',
            name='sba_other',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3),
        ),
    ]
