# Generated by Django 2.0.4 on 2018-06-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0011_auto_20180625_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lender',
            old_name='cell_phone',
            new_name='lender_cell_phone',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='city',
            new_name='lender_city',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='company',
            new_name='lender_company',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='first_name',
            new_name='lender_first_name',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='last_name',
            new_name='lender_last_name',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='personal_email',
            new_name='lender_personal_email',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='solicitation',
            new_name='lender_solicitation',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='state',
            new_name='lender_state',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='street_address',
            new_name='lender_street_address',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='work_email',
            new_name='lender_work_email',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='work_phone',
            new_name='lender_work_phone',
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='zip_code',
            new_name='lender_zip_code',
        ),
    ]
