# Generated by Django 2.0.4 on 2018-06-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0012_auto_20180627_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('client_last_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('client_company', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('client_street_address', models.CharField(default=None, max_length=200, null=True)),
                ('client_city', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('client_state', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('client_zip_code', models.IntegerField(default=None, null=True)),
                ('client_work_email', models.EmailField(blank=True, default=None, max_length=200, null=True)),
                ('client_personal_email', models.EmailField(blank=True, default=None, max_length=200, null=True)),
                ('client_work_phone', models.IntegerField(blank=True, default=None, null=True)),
                ('client_cell_phone', models.IntegerField(blank=True, default=None, null=True)),
                ('business_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('business_main_phone', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('business_website', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('business_type', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('business_year_established', models.IntegerField(blank=True, default=None, null=True)),
                ('property_address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('property_value', models.IntegerField(blank=True, default=None, null=True)),
                ('loan_desc', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('loan_type', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='qual_single_tennant',
            new_name='qual_single_tenant',
        ),
    ]
