# Generated by Django 2.0.4 on 2018-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0013_auto_20180629_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='POC_business',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3),
        ),
        migrations.AddField(
            model_name='loan',
            name='POC_cell_phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='POC_name',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3),
        ),
        migrations.AddField(
            model_name='loan',
            name='POC_work_phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='client_using_poc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3),
        ),
        migrations.AddField(
            model_name='loan',
            name='poc_email',
            field=models.EmailField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
