# Generated by Django 2.0.4 on 2018-06-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0015_auto_20180630_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='client_company',
        ),
        migrations.AddField(
            model_name='loan',
            name='client_company_city',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='client_company_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='client_company_state',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='client_company_street_address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='client_company_zip',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='client_occupation',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
