# Generated by Django 2.0.4 on 2018-06-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0016_auto_20180630_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_dcsr',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_to_value',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Owner Occupied', 'Owner Occupied'), ('Investment', 'Investment'), ('Construction', 'Construction'), ('SBA', 'SBA')], default='No', max_length=3),
        ),
    ]
