# Generated by Django 2.0.4 on 2018-06-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0017_auto_20180630_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='fin_bankruptcy',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='loan',
            name='fin_fico',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='fin_monthly_payments',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='fin_owns_home',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='loan',
            name='fin_salary',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='fin_short_sale',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='loan',
            name='fin_total_debt',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='fin_years_in_business',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
