# Generated by Django 2.0.4 on 2018-07-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0019_auto_20180630_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_desc',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
