# Generated by Django 2.0.4 on 2018-07-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0020_auto_20180630_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='mf_2to4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3),
        ),
        migrations.AddField(
            model_name='lender',
            name='mf_gt4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unk', 'Unk')], default='Unk', max_length=3),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Owner Occupied', 'Owner Occupied'), ('Investment', 'Investment'), ('Construction', 'Construction'), ('SBA', 'SBA')], default='SBA', max_length=3),
        ),
    ]
