# Generated by Django 2.0.4 on 2018-07-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0022_auto_20180708_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='docs_appraisal',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='loan',
            name='docs_brokers_opinion',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
