# Generated by Django 2.0.4 on 2018-07-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0023_auto_20180708_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='poc_email',
            new_name='POC_email',
        ),
    ]
