# Generated by Django 2.0.4 on 2018-07-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0027_auto_20180708_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_dcsr',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_desc',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_to_value',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Owner Occupied', 'Owner Occupied'), ('Investment', 'Investment'), ('Construction', 'Construction'), ('SBA', 'SBA')], default='SBA', max_length=3),
        ),
    ]
