# Generated by Django 2.0.4 on 2018-07-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0028_auto_20180708_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Owner Occupied', 'Owner Occupied'), ('Investment', 'Investment'), ('Construction', 'Construction'), ('SBA', 'SBA')], default='Owner Occupied', max_length=30),
        ),
    ]
