# Generated by Django 2.0.4 on 2018-07-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0029_auto_20180708_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_type',
        ),
    ]
