# Generated by Django 2.0.4 on 2018-07-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0032_auto_20180708_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='business_main_phone',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='business_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='business_type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='business_website',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='business_year_established',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
